import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import jwt from "jsonwebtoken";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { logoutUser } from "@/redux/actions/auth";
import { getCookie } from "cookies-next";

export const getServerSideProps = async ({ req, res }) => {
  const token = getCookie("user_token", { req, res });
  
  if (!token) return { props: { isAuthenticated: false } };

  try {
    const isAuthenticated = await jwt.verify(
      token,
      "soccerscouting4u-secret-key"
    );
    return { props: { isAuthenticated: isAuthenticated } };
  } catch (err) {
    return { props: { isAuthenticated: false } };
  }
};

export default function Home({ isAuthenticated }) {
  const dispatch = useDispatch();
  const isLoggedIn = useSelector((state) => state.auth?.isLoggedIn);
  const router = useRouter();

  useEffect(() => {
    // rome-ignore lint/complexity/useSimplifiedLogicExpression: <explanation>
    if (!isAuthenticated || !isLoggedIn) {
      dispatch(logoutUser());
    }
  }, [isAuthenticated, isLoggedIn]);

  return (
    <>
      <Head>
        <title>Arrimo Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}
